# https://docs.docker.com/compose/compose-file/

services:
  mlflow:
    image: ghcr.io/mlflow/mlflow:v{{cookiecutter.mlflow_version}}
    ports:
      - 5000:5000
    environment:
      - MLFLOW_HOST=0.0.0.0
    command: mlflow server